import { Hotspot, Guide, BirdSpecies } from './types';

export const HOTSPOTS: Hotspot[] = [
  {
    id: '1',
    name: 'Mabamba Swamp',
    country: 'Uganda',
    description: 'A large wetland on the edge of Lake Victoria, famous for the elusive Shoebill Stork.',
    keySpecies: ['Shoebill', 'Papyrus Gonolek', 'Blue-breasted Bee-eater'],
    coordinates: { lat: 0.093, lng: 32.234 },
    imageUrl: 'https://picsum.photos/800/600?random=1',
    difficulty: 'Easy'
  },
  {
    id: '2',
    name: 'Bwindi Impenetrable Forest',
    country: 'Uganda',
    description: 'Prime montane forest famous for Gorillas and Albertine Rift endemics.',
    keySpecies: ['African Green Broadbill', 'Shelley’s Crimsonwing'],
    coordinates: { lat: -1.053, lng: 29.615 },
    imageUrl: 'https://picsum.photos/800/600?random=2',
    difficulty: 'Hard'
  },
  {
    id: '3',
    name: 'Nyungwe National Park',
    country: 'Rwanda',
    description: 'A vast untouched tropical rainforest with a high canopy walk.',
    keySpecies: ['Rwenzori Turaco', 'Red-collared Babbler'],
    coordinates: { lat: -2.483, lng: 29.231 },
    imageUrl: 'https://picsum.photos/800/600?random=3',
    difficulty: 'Moderate'
  },
  {
    id: '4',
    name: 'Akagera National Park',
    country: 'Rwanda',
    description: 'Savannah park with wetlands, great for waterbirds and raptors.',
    keySpecies: ['Red-faced Barbet', 'Papyrus Gonolek', 'Fish Eagle'],
    coordinates: { lat: -1.883, lng: 30.716 },
    imageUrl: 'https://picsum.photos/800/600?random=4',
    difficulty: 'Easy'
  }
];

export const GUIDES: Guide[] = [
  {
    id: 'g1',
    name: 'Moses K.',
    location: 'Entebbe, Uganda',
    rating: 4.9,
    specialties: ['Wetlands', 'Shoebill'],
    imageUrl: 'https://picsum.photos/200/200?random=5'
  },
  {
    id: 'g2',
    name: 'Grace A.',
    location: 'Kigali, Rwanda',
    rating: 4.8,
    specialties: ['Montane Forest', 'Photography'],
    imageUrl: 'https://picsum.photos/200/200?random=6'
  },
  {
    id: 'g3',
    name: 'John B.',
    location: 'Bwindi, Uganda',
    rating: 5.0,
    specialties: ['Endemics', 'Hiking'],
    imageUrl: 'https://picsum.photos/200/200?random=7'
  }
];

export const BIRD_SPECIES: BirdSpecies[] = [
  {
    id: 'b1',
    commonName: 'Shoebill',
    scientificName: 'Balaeniceps rex',
    description: 'A massive, prehistoric-looking bird with a shoe-shaped bill which is straw-colored with erratic greyish markings. The plumage is predominantly blue-grey with darker flight feathers. Standing up to 1.5m tall, it has long legs and large feet ideal for walking on floating vegetation. It hunts by standing absolutely still for long periods before striking lungfish.',
    category: 'Waterbird',
    colors: ['Grey', 'Blue'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Balaeniceps_rex.jpg/640px-Balaeniceps_rex.jpg',
    size: 'Very Large (1.5m)',
    status: 'Endangered',
    distribution: 'Mabamba Swamp, Murchison Falls (Delta), Lake Mburo, Akagera.',
    habitat: 'Freshwater swamps, specifically those with extensive papyrus beds and lungfish populations.',
    iucnStatus: 'VU'
  },
  {
    id: 'b2',
    commonName: 'Grey Crowned Crane',
    scientificName: 'Balearica regulorum',
    description: 'The national bird of Uganda, easily recognized by its stiff, golden-yellow crest feathers. It has a grey body, white wings with gold and chestnut feathers, and a bright red throat pouch (wattle). They are non-migratory and often found in pairs performing elaborate courtship dances involving bowing and jumping.',
    category: 'Waterbird',
    colors: ['Grey', 'Gold', 'White', 'Red'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Grey_crowned_crane_%28Balearica_regulorum_gibbericeps%29_head.jpg/640px-Grey_crowned_crane_%28Balearica_regulorum_gibbericeps%29_head.jpg',
    size: 'Large (1m)',
    status: 'Endangered',
    distribution: 'Wetlands and grasslands throughout Uganda and Rwanda (Akagera).',
    habitat: 'Dry and wet open habitats, preferring marshes, damp grasslands, and lake edges.',
    iucnStatus: 'EN'
  },
  {
    id: 'b3',
    commonName: 'Great Blue Turaco',
    scientificName: 'Corythaeola cristata',
    description: 'The largest turaco species. It features vivid blue upperparts, a yellow breast fading to red on the belly, and a prominent blue-black crest. Its beak is yellow with a red tip. Known for its loud, bubbling calls that resonate through the rainforest canopy.',
    category: 'Forest',
    colors: ['Blue', 'Yellow', 'Red'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Great_Blue_Turaco.jpg/640px-Great_Blue_Turaco.jpg',
    size: 'Large (75cm)',
    status: 'Common',
    distribution: 'Kibale Forest, Bigodi Wetland, Nyungwe Forest, Entebbe Botanical Gardens.',
    habitat: 'Montane and lowland tropical rainforests, gallery forests, and tall savannah trees.',
    iucnStatus: 'LC'
  },
  {
    id: 'b4',
    commonName: 'Lilac-breasted Roller',
    scientificName: 'Coracias caudatus',
    description: 'Famous for its acrobatic flight and stunning pastel plumage. It has a lilac throat and breast, turquoise belly, and bright blue wing patches. The face is washed with white and light green. It often perches on dead branches or telephone wires scanning for insects and lizards.',
    category: 'Savannah',
    colors: ['Blue', 'Lilac', 'Green', 'Brown'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Lilac-breasted_roller_%28Coracias_caudatus_caudatus%29_Botswana.jpg/640px-Lilac-breasted_roller_%28Coracias_caudatus_caudatus%29_Botswana.jpg',
    size: 'Medium (36cm)',
    status: 'Common',
    distribution: 'Murchison Falls, Queen Elizabeth NP, Akagera National Park.',
    habitat: 'Open woodland and savannah; prefers areas with widely spaced trees for perching.',
    iucnStatus: 'LC'
  },
  {
    id: 'b5',
    commonName: 'African Fish Eagle',
    scientificName: 'Haliaeetus vocifer',
    description: 'A distinctive raptor with a white head, chest, and tail contrasting with a dark chestnut body and black wings. The face is bare and yellow. Known for its iconic, ringing call "weee-ah, hyo-hyo-hyo" often heard near lakes and rivers.',
    category: 'Raptor',
    colors: ['Brown', 'White', 'Black'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Haliaeetus_vocifer_-_Chobe_01.jpg/640px-Haliaeetus_vocifer_-_Chobe_01.jpg',
    size: 'Large (70cm)',
    status: 'Common',
    distribution: 'Lake Victoria, Kazinga Channel, Lake Ihema (Akagera), Nile River.',
    habitat: 'Large bodies of open water with abundant fish supply and tall trees for perching.',
    iucnStatus: 'LC'
  },
  {
    id: 'b6',
    commonName: 'Rwenzori Turaco',
    scientificName: 'Ruwenzorornis johnstoni',
    description: 'An Albertine Rift endemic restricted to high-altitude forests. It has plumage of varying shades of green, with a peach-colored throat and a distinctive crimson patch on the nape. In flight, it reveals brilliant crimson wing patches.',
    category: 'Forest',
    colors: ['Green', 'Blue', 'Red'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Ruwenzori_Turaco_%28Ruwenzorornis_johnstoni_kivuensis%29.jpg/640px-Ruwenzori_Turaco_%28Ruwenzorornis_johnstoni_kivuensis%29.jpg',
    size: 'Medium (45cm)',
    status: 'Endemic',
    distribution: 'Nyungwe National Park, Bwindi Impenetrable Forest, Mgahinga Gorilla NP.',
    habitat: 'Montane forests, particularly in the bamboo zone and Hagenia-Hypericum woodlands.',
    iucnStatus: 'LC'
  },
  {
    id: 'b7',
    commonName: 'Malachite Kingfisher',
    scientificName: 'Corythornis cristatus',
    description: 'A tiny, jewel-like bird with a bright metallic blue head and back, and rufous underparts. It has a distinctive crest of green and black feathers that can be raised. The bill is bright red. Often seen perching low over water on reeds.',
    category: 'Waterbird',
    colors: ['Blue', 'Orange', 'White'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Malachite_Kingfisher_%28Corythornis_cristatus%29.jpg/640px-Malachite_Kingfisher_%28Corythornis_cristatus%29.jpg',
    size: 'Small (13cm)',
    status: 'Common',
    distribution: 'Widespread near water bodies; Queen Elizabeth NP, Lake Mburo, Akagera.',
    habitat: 'Slow-moving water with reeds and aquatic vegetation for perching.',
    iucnStatus: 'LC'
  },
  {
    id: 'b8',
    commonName: 'Red-throated Bee-eater',
    scientificName: 'Merops bulocki',
    description: 'A stunning bee-eater with a vibrant bright red throat, green upperparts, and a buffy-yellow breast. It has a black mask and a square tail. These birds are highly social and nest in colonies in riverbanks.',
    category: 'Savannah',
    colors: ['Green', 'Red', 'Yellow'],
    regions: ['Uganda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Red-throated_Bee-eater_%28Merops_bulocki%29.jpg/640px-Red-throated_Bee-eater_%28Merops_bulocki%29.jpg',
    size: 'Small (22cm)',
    status: 'Common',
    distribution: 'Common in Murchison Falls NP and along the Nile River banks.',
    habitat: 'Wooded savannahs, riparian woodlands, and eroded gullies suitable for nesting.',
    iucnStatus: 'LC'
  },
  {
    id: 'b9',
    commonName: 'Saddle-billed Stork',
    scientificName: 'Ephippiorhynchus senegalensis',
    description: 'A very tall, striking stork with iridescent black head, neck, back, and wings, and white underparts. Its massive bill is red with a black band and a yellow frontal shield (saddle). Males have dark eyes and wattles; females have yellow eyes.',
    category: 'Waterbird',
    colors: ['Black', 'White', 'Red', 'Yellow'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Saddle-billed_Stork_%28Ephippiorhynchus_senegalensis%29_Male.jpg/640px-Saddle-billed_Stork_%28Ephippiorhynchus_senegalensis%29_Male.jpg',
    size: 'Very Large (1.5m)',
    status: 'Common',
    distribution: 'Murchison Falls, Queen Elizabeth NP, Akagera National Park.',
    habitat: 'Large freshwater wetlands, floodplains, and open shallow water bodies.',
    iucnStatus: 'LC'
  },
  {
    id: 'b10',
    commonName: 'Regal Sunbird',
    scientificName: 'Cinnyris regius',
    description: 'A stunning Albertine Rift Endemic found in highland forests. The male has iridescent green upperparts, head, and throat, with a bright red central breast stripe bordered by yellow on the sides. Females are dull olive-green.',
    category: 'Forest',
    colors: ['Green', 'Red', 'Yellow'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Regal_Sunbird.jpg/640px-Regal_Sunbird.jpg',
    size: 'Small (12cm)',
    status: 'Endemic',
    distribution: 'Nyungwe Forest, Bwindi Impenetrable Forest, Rwenzori Mountains.',
    habitat: 'Montane forests, particularly edges and clearings with flowering plants.',
    iucnStatus: 'LC'
  },
  {
    id: 'b11',
    commonName: 'Black-and-white-casqued Hornbill',
    scientificName: 'Bycanistes subcylindricus',
    description: 'A large, black-and-white hornbill with a massive casque on the bill (larger in males). It has black plumage with a white rump and tail sides. In flight, it shows broad white wing patches. Known for loud, braying calls.',
    category: 'Forest',
    colors: ['Black', 'White'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Black-and-white-casqued_Hornbill.jpg/640px-Black-and-white-casqued_Hornbill.jpg',
    size: 'Large (70cm)',
    status: 'Common',
    distribution: 'Forests and woodlands; Kibale, Mabira, Entebbe, Nyungwe borders.',
    habitat: 'Evergreen and gallery forests, secondary growth, and mature plantations.',
    iucnStatus: 'LC'
  },
  {
    id: 'b12',
    commonName: 'Ross\'s Turaco',
    scientificName: 'Musophaga rossae',
    description: 'A sleek, deep blue-violet turaco with a crimson crest and bright yellow facial skin (mask). The bill is yellow. In flight, it displays brilliant crimson primary feathers, typical of turacos. It is generally quieter than other turacos.',
    category: 'Forest',
    colors: ['Blue', 'Purple', 'Yellow', 'Red'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Musophaga_rossae_-near_Kampala%2C_Uganda-8.jpg/640px-Musophaga_rossae_-near_Kampala%2C_Uganda-8.jpg',
    size: 'Medium (50cm)',
    status: 'Common',
    distribution: 'Woodlands and forest edges; Lake Mburo, Akagera, Kampala suburbs.',
    habitat: 'Riverine forests, broad-leaved woodlands, and humid forest edges.',
    iucnStatus: 'LC'
  },
  {
    id: 'b13',
    commonName: 'Hamerkop',
    scientificName: 'Scopus umbretta',
    description: 'A medium-sized, all-brown wading bird with a unique head shape created by a long bill and a backward-projecting crest, resembling a hammer. It builds massive, domed stick nests in tree forks, often weighing over 50kg.',
    category: 'Waterbird',
    colors: ['Brown'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Hamerkop_%28Scopus_umbretta%29.jpg/640px-Hamerkop_%28Scopus_umbretta%29.jpg',
    size: 'Medium (56cm)',
    status: 'Common',
    distribution: 'Widespread near any water body; wetlands, rivers, roadside ditches.',
    habitat: 'Wetlands, rice paddies, savannas with water, and riparian woodlands.',
    iucnStatus: 'LC'
  },
  {
    id: 'b14',
    commonName: 'Woodland Kingfisher',
    scientificName: 'Halcyon senegalensis',
    description: 'A medium-sized kingfisher with a bright electric blue back, wing panel, and tail. The head and underparts are white/grey, and it has a black eye stripe. The bill is bicolored: red on top, black on bottom. Known for its loud, trilling call.',
    category: 'Savannah',
    colors: ['Blue', 'White', 'Black', 'Red'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Woodland_Kingfisher_%28Halcyon_senegalensis%29.jpg/640px-Woodland_Kingfisher_%28Halcyon_senegalensis%29.jpg',
    size: 'Small (23cm)',
    status: 'Common',
    distribution: 'Wooded savannahs and gardens; Murchison Falls, Queen Elizabeth NP, Akagera.',
    habitat: 'Wooded savannah, acacia woodlands, parks, and large gardens.',
    iucnStatus: 'LC'
  },
  {
    id: 'b15',
    commonName: 'African Jacana',
    scientificName: 'Actophilornis africanus',
    description: 'Recognizable by its chestnut body, golden neck, white face/throat, and light blue frontal shield. Its defining feature is its extremely long toes and claws, which distribute its weight, allowing it to walk on floating lily pads.',
    category: 'Waterbird',
    colors: ['Chestnut', 'White', 'Black', 'Blue'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/African_Jacana_%28Actophilornis_africanus%29.jpg/640px-African_Jacana_%28Actophilornis_africanus%29.jpg',
    size: 'Medium (30cm)',
    status: 'Common',
    distribution: 'Wetlands with floating vegetation; Lake Mburo, Kazinga Channel, Akagera.',
    habitat: 'Shallow lakes, ponds, and slow-moving rivers with floating vegetation like water lilies.',
    iucnStatus: 'LC'
  },
  {
    id: 'b16',
    commonName: 'Marabou Stork',
    scientificName: 'Leptoptilos crumenifer',
    description: 'A massive, scavenger stork with a naked, pinkish head and neck, a white ruff, and a large hanging throat sac. It has black wings and a white belly. Often looks "grumpy" or hunched. Scavenges on carrion and urban waste.',
    category: 'Savannah',
    colors: ['Black', 'White', 'Pink'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Leptoptilos_crumeniferus_-_Marabou_Stork.jpg/640px-Leptoptilos_crumeniferus_-_Marabou_Stork.jpg',
    size: 'Very Large (1.5m)',
    status: 'Common',
    distribution: 'Savannahs and urban centers; Kampala, Queen Elizabeth NP, Akagera.',
    habitat: 'Open dry savannahs, grasslands, swamps, and near human habitation (fishing villages, dumps).',
    iucnStatus: 'LC'
  },
  {
    id: 'b17',
    commonName: 'Secretarybird',
    scientificName: 'Sagittarius serpentarius',
    description: 'A large, terrestrial bird of prey with an eagle-like body on crane-like legs. It has a crest of black feathers, a grey body, black flight feathers, and black thighs (resembling breeches). It hunts snakes and insects by stomping on them.',
    category: 'Raptor',
    colors: ['Grey', 'Black', 'White'],
    regions: ['Uganda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Secretary_bird_%28Sagittarius_serpentarius%29.jpg/640px-Secretary_bird_%28Sagittarius_serpentarius%29.jpg',
    size: 'Large (1.3m)',
    status: 'Endangered',
    distribution: 'Open plains and grasslands; Kidepo Valley National Park.',
    habitat: 'Open grasslands, savannahs, and steppe with short grass.',
    iucnStatus: 'EN'
  },
  {
    id: 'b18',
    commonName: 'Pin-tailed Whydah',
    scientificName: 'Vidua macroura',
    description: 'Breeding males are conspicuous with a long, flowing black tail (up to 20cm), black back and crown, and white underparts and collar. The bill is bright red. Non-breeding males and females are sparrow-like with brown streaks.',
    category: 'Savannah',
    colors: ['Black', 'White', 'Red'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Pin-tailed_Whydah_%28Vidua_macroura%29_Male.jpg/640px-Pin-tailed_Whydah_%28Vidua_macroura%29_Male.jpg',
    size: 'Small (12cm + 20cm tail)',
    status: 'Common',
    distribution: 'Open habitats, gardens, and scrubland throughout both countries.',
    habitat: 'Grasslands, open savannahs, gardens, and cultivated areas.',
    iucnStatus: 'LC'
  },
  {
    id: 'b19',
    commonName: 'African Green Broadbill',
    scientificName: 'Pseudocalyptomena graueri',
    description: 'A tiny, rotund, bright green bird with fine black streaking on the head and breast and a light blue throat. It is an extremely rare Albertine Rift Endemic, often sitting motionless in the canopy, making it difficult to spot.',
    category: 'Forest',
    colors: ['Green', 'Blue'],
    regions: ['Uganda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/African_Green_Broadbill.jpg/640px-African_Green_Broadbill.jpg',
    size: 'Small (14cm)',
    status: 'Endangered',
    distribution: 'Restricted to the Ruhija sector of Bwindi Impenetrable Forest.',
    habitat: 'Primary montane forest, often associated with bamboo stands.',
    iucnStatus: 'VU'
  },
  {
    id: 'b20',
    commonName: 'Papyrus Gonolek',
    scientificName: 'Laniarius mufumbiri',
    description: 'A striking bird with a jet-black head, back, and wings, and vivid crimson-red underparts. It has a yellow crown patch (gonolek means "crowned"). It is a shy, skulking bird restricted entirely to papyrus swamps, known for its duet calls.',
    category: 'Waterbird',
    colors: ['Black', 'Red', 'Yellow'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Papyrus_Gonolek.jpg/640px-Papyrus_Gonolek.jpg',
    size: 'Medium (18cm)',
    status: 'Rare',
    distribution: 'Papyrus swamps; Mabamba, Lake Mburo, Queen Elizabeth NP, Akagera.',
    habitat: 'Strictly limited to Papyrus swamps and adjacent reedbeds.',
    iucnStatus: 'NT'
  },
  {
    id: 'b21',
    commonName: 'African Paradise Flycatcher',
    scientificName: 'Terpsiphone viridis',
    description: 'Males occur in two morphs: white or rufous (chestnut), both with glossy black heads and extremely long tail streamers. Females are rufous with shorter tails. They are active, noisy birds, constantly flitting through trees catching insects.',
    category: 'Forest',
    colors: ['White', 'Red', 'Black', 'Blue'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/African_Paradise-Flycatcher_%28Terpsiphone_viridis%29_male_white_morph.jpg/640px-African_Paradise-Flycatcher_%28Terpsiphone_viridis%29_male_white_morph.jpg',
    size: 'Medium (17cm + 18cm tail)',
    status: 'Common',
    distribution: 'Widespread in forests, gardens, and woodlands throughout Uganda and Rwanda.',
    habitat: 'Riverine forests, woodlands, savannah edges, and gardens.',
    iucnStatus: 'LC'
  },
  {
    id: 'b22',
    commonName: 'Black-headed Gonolek',
    scientificName: 'Laniarius erythrogaster',
    description: 'A striking bush-shrike with a jet-black upper body and bright crimson-red underparts. Unlike the Papyrus Gonolek, it has no yellow crown. It is vocal, often singing in duets, and is found in drier scrub and gardens rather than swamps.',
    category: 'Savannah',
    colors: ['Black', 'Red'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black-headed_Gonolek.jpg/640px-Black-headed_Gonolek.jpg',
    size: 'Medium (20cm)',
    status: 'Common',
    distribution: 'Savannahs, scrub, and hotel gardens; Murchison Falls, Queen Elizabeth NP.',
    habitat: 'Dense scrub, thickets in savannah, and large gardens.',
    iucnStatus: 'LC'
  },
  {
    id: 'b23',
    commonName: 'Pied Kingfisher',
    scientificName: 'Ceryle rudis',
    description: 'A black and white kingfisher famous for its ability to hover over water before diving for fish. Males have two black breast bands, while females have one. It is noisy and gregarious, often seen in pairs or small family groups.',
    category: 'Waterbird',
    colors: ['Black', 'White'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Pied_Kingfisher_%28Ceryle_rudis%29_hovering.jpg/640px-Pied_Kingfisher_%28Ceryle_rudis%29_hovering.jpg',
    size: 'Medium (25cm)',
    status: 'Common',
    distribution: 'Any open water; Lake Victoria, Kazinga Channel, Nile River, Lake Ihema.',
    habitat: 'Rivers, lakes, estuaries, and lagoons, preferring clear water.',
    iucnStatus: 'LC'
  },
  {
    id: 'b24',
    commonName: 'Hadada Ibis',
    scientificName: 'Bostrychia hagedash',
    description: 'A large, dull grey-brown ibis with a curved bill and a splash of iridescent purple/green on the wings. It is most famous for its incredibly loud, raucous "haa-haa-haa-de-dah" call, often heard at dawn and dusk.',
    category: 'Waterbird',
    colors: ['Grey', 'Brown', 'Purple'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Hadada_Ibis_%28Bostrychia_hagedash%29.jpg/640px-Hadada_Ibis_%28Bostrychia_hagedash%29.jpg',
    size: 'Large (76cm)',
    status: 'Common',
    distribution: 'Widespread in wetlands, gardens, and playing fields throughout the region.',
    habitat: 'Wooded streams, marshes, grasslands, and urban areas.',
    iucnStatus: 'LC'
  },
  {
    id: 'b25',
    commonName: 'Village Weaver',
    scientificName: 'Ploceus cucullatus',
    description: 'A bold, noisy bird. Breeding males are bright yellow with a black head/mask and red eye. They build intricate woven nests in large, noisy colonies hanging from trees, often in villages and lodges. Females are olive-yellow.',
    category: 'Savannah',
    colors: ['Yellow', 'Black'],
    regions: ['Uganda', 'Rwanda'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Village_Weaver_%28Ploceus_cucullatus%29_male_building_nest.jpg/640px-Village_Weaver_%28Ploceus_cucullatus%29_male_building_nest.jpg',
    size: 'Small (15cm)',
    status: 'Common',
    distribution: 'Ubiquitous near human settlements and savannahs in both countries.',
    habitat: 'Savannah, open woodlands, farmland, villages, and towns.',
    iucnStatus: 'LC'
  }
];